/*
 * Copyright (c) 2013 Net7 SRL, <http://www.netseven.it/>
 * 
 * This file is part of Pundit: Annonation Server.
 * 
 * Pundit: Annonation Server is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Pundit: Annonation Server is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Pundit: Annonation Server.  If not, see <http ://www.gnu.org/licenses/>.
 *
 * See LICENSE.TXT or visit <http://thepund.it> for the full text of the license.
 */
package eu.semlibproject.annotationserver.hibernate;
// Generated 25-set-2012 10.31.34 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Notebooks generated by hbm2java
 */
public class Notebooks  implements java.io.Serializable {


     private String id;
     private String ownerid;
     private boolean public_;
     private Set<Annotations> annotationses = new HashSet<Annotations>(0);
     private Set<Currentnotebooks> currentnotebookses = new HashSet<Currentnotebooks>(0);
     private Set<Permissions> permissionses = new HashSet<Permissions>(0);
     private Set<Activenotebooks> activenotebookses = new HashSet<Activenotebooks>(0);

    public Notebooks() {
    }

	
    public Notebooks(String id, String ownerid, boolean public_) {
        this.id = id;
        this.ownerid = ownerid;
        this.public_ = public_;
    }
    public Notebooks(String id, String ownerid, boolean public_, Set<Annotations> annotationses, Set<Currentnotebooks> currentnotebookses, Set<Permissions> permissionses, Set<Activenotebooks> activenotebookses) {
       this.id = id;
       this.ownerid = ownerid;
       this.public_ = public_;
       this.annotationses = annotationses;
       this.currentnotebookses = currentnotebookses;
       this.permissionses = permissionses;
       this.activenotebookses = activenotebookses;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getOwnerid() {
        return this.ownerid;
    }
    
    public void setOwnerid(String ownerid) {
        this.ownerid = ownerid;
    }
    public boolean isPublic_() {
        return this.public_;
    }
    
    public void setPublic_(boolean public_) {
        this.public_ = public_;
    }
    public Set<Annotations> getAnnotationses() {
        return this.annotationses;
    }
    
    public void setAnnotationses(Set<Annotations> annotationses) {
        this.annotationses = annotationses;
    }
    public Set<Currentnotebooks> getCurrentnotebookses() {
        return this.currentnotebookses;
    }
    
    public void setCurrentnotebookses(Set<Currentnotebooks> currentnotebookses) {
        this.currentnotebookses = currentnotebookses;
    }
    public Set<Permissions> getPermissionses() {
        return this.permissionses;
    }
    
    public void setPermissionses(Set<Permissions> permissionses) {
        this.permissionses = permissionses;
    }
    public Set<Activenotebooks> getActivenotebookses() {
        return this.activenotebookses;
    }
    
    public void setActivenotebookses(Set<Activenotebooks> activenotebookses) {
        this.activenotebookses = activenotebookses;
    }




}


